Token type added to the events.
jdkanani/fx-portal pull request #15
Opened 2021-08-23 08:08 UTC by reddyismav

2021-08-23 08:56 UTC, QEDK approved these changes
LGTM!

2021-08-25 10:23 UTC, rahuldamodar94 approved these changes

2021-08-25 10:31 UTC, jdkanani approved these changes

2021-08-25 10:34 UTC, jdkanani requested changes

2021-08-25 10:34 UTC, jdkanani commented on contracts/examples/erc1155-transfer/FxERC1155RootTunnel.sol
> +    event FxDepositBatchERC1155(address indexed rootToken, address userAddress, uint256[] ids, uint256[] amounts);
Make `userAddress` indexed?

2021-08-25 10:34 UTC, jdkanani commented on contracts/examples/erc1155-transfer/FxERC1155RootTunnel.sol
> +    event FxWithdrawERC1155(address indexed rootToken, address indexed childToken, address userAddress, uint256 id, uint256 amount);
Make `userAddress` indexed?

2021-08-25 10:34 UTC, jdkanani commented on contracts/examples/erc1155-transfer/FxERC1155RootTunnel.sol
> +    event FxDepositERC1155(address indexed rootToken, address indexed userAddress, uint256 id, uint256 amount);
Add depositor?

2021-08-25 10:34 UTC, jdkanani commented on contracts/examples/erc20-transfer/FxERC20RootTunnel.sol
> +        emit FxDepositERC20(rootToken, user, amount);
Add depositor?

2021-08-25 10:34 UTC, jdkanani commented on contracts/examples/erc721-transfer/FxERC721RootTunnel.sol
> +        emit FxDepositERC721(rootToken, user, tokenId);
Add `depositor`?

2021-08-26 07:06 UTC, reddyismav commented on contracts/examples/erc721-transfer/FxERC721RootTunnel.sol
> +        emit FxDepositERC721(rootToken, user, tokenId);
Done

2021-08-26 07:06 UTC, reddyismav commented on contracts/examples/erc20-transfer/FxERC20RootTunnel.sol
> +        emit FxDepositERC20(rootToken, user, amount);
Done

2021-08-26 07:07 UTC, reddyismav commented on contracts/examples/erc1155-transfer/FxERC1155RootTunnel.sol
> +    event FxDepositERC1155(address indexed rootToken, address indexed userAddress, uint256 id, uint256 amount);
Done

2021-08-26 07:07 UTC, reddyismav commented on contracts/examples/erc1155-transfer/FxERC1155RootTunnel.sol
> +    event FxWithdrawERC1155(address indexed rootToken, address indexed childToken, address userAddress, uint256 id, uint256 amount);
Yep! Done!

2021-08-26 07:07 UTC, reddyismav commented on contracts/examples/erc1155-transfer/FxERC1155RootTunnel.sol
> +    event FxDepositBatchERC1155(address indexed rootToken, address userAddress, uint256[] ids, uint256[] amounts);
Done!

2021-08-27 10:38 UTC, jdkanani approved these changes

2021-08-27 10:38 UTC, merged