Feature/hardhat unittest
jdkanani/fx-portal pull request #26
Opened 2021-11-25 08:50 UTC by zorancuc

hardhat configuration
unit-test of tokens

2022-01-26 11:45 UTC, imyourm8 requested changes
Looks good, just need some clean up from logging in contracts and comments in the code - we don't need commented code when we have git for the history

2022-01-26 11:45 UTC, imyourm8 commented on contracts/FxChild.sol
> +import "hardhat/console.sol";
please remove logging from all contracts, simulation contracts can keep logs as they are test related

2022-01-26 11:45 UTC, imyourm8 commented on test/shared/utilities.ts
> +  // });
remove comments

2022-01-27 03:47 UTC, zorancuc commented on test/shared/utilities.ts
> +  // });
OK

2022-02-17 13:17 UTC, jdkanani commented
Can you fix the conflict and make sure ci works

2022-03-03 12:44 UTC, jdkanani commented
Adding @wschwab

2023-05-19 11:33 UTC, closed without merging