Add support for ERC721, ERC1155, modify ERC20
jdkanani/fx-portal pull request #6
Opened 2021-04-28 10:51 UTC by QEDK

* Add ERC721 tunnels for transfer
* Add ERC1155 tunnels for transfer
* Modify transfer behaviour for ERC20 to avoid approvals
* Add required interfaces and libraries

Cc @Raneet10 @pranavdaa

2021-04-28 21:03 UTC, jdkanani requested changes
Thank you very much for the PR.

2021-04-28 21:03 UTC, jdkanani commented on contracts/tokens/FxERC721.sol
> +        require(msg.sender == _fxManager, "Invalid sender");
Why restrict to fxManager? Anyone should be able to transfer their owned NFTs.

2021-04-28 21:03 UTC, jdkanani commented on contracts/tokens/IFxERC1155.sol
> +}
Please add a new line at end of the file. 

Same for all files.

2021-04-28 21:03 UTC, jdkanani commented on contracts/tokens/IFxERC721.sol
> +    function transfer(address from, address to, uint256 tokenId) external;
Do we need this? Because transfer will be available by default.

2021-04-28 21:03 UTC, jdkanani commented on contracts/tokens/FxERC1155.sol
> +}
Please add a new line at end of the file.

2021-04-28 21:03 UTC, jdkanani commented on contracts/lib/Address.sol
> +    function isContract(address account) internal view returns (bool) {
Can we use this everywhere (in fx child tunnel contracts) since we are using the library now? 

Maybe in the next PR.

2021-04-28 21:03 UTC, jdkanani commented on contracts/examples/erc1155-transfer/FxERC1155RootTunnel.sol
> +        string memory uri = rootTokenContract.uri(0); //token Id?
Do we need `uri` while mapping?

2021-04-28 21:03 UTC, jdkanani commented on contracts/examples/erc1155-transfer/FxERC1155RootTunnel.sol
> +        rootToChildTokens[rootToken] = childToken;
We should also generate an event for mapping for the graph node or something.

Same for ERC20, ERC721.

2021-04-28 21:03 UTC, jdkanani commented on contracts/examples/erc1155-transfer/FxERC1155RootTunnel.sol
> +            _syncTransfer(syncData);
```suggestion
            _syncWithdraw(syncData);
```

2021-04-28 21:03 UTC, jdkanani commented on contracts/examples/erc1155-transfer/FxERC1155RootTunnel.sol
> +            _syncBatchTransfer(syncData);
```suggestion
            _syncBatchWithdraw(syncData);
```

2021-04-29 04:12 UTC, Raneet10 commented on contracts/examples/erc1155-transfer/FxERC1155RootTunnel.sol
> +        string memory uri = rootTokenContract.uri(0); //token Id?
To the best of my knowledge, `uri` is the only metadata for a ERC 1155 token and might be required while initialising the child token. Hence we send the `uri` to child tunnel (similar to  `name`, `symbol` and/or `amount`  for  ERC-20/721 )

2021-04-29 07:41 UTC, QEDK commented on contracts/tokens/FxERC721.sol
> +        require(msg.sender == _fxManager, "Invalid sender");
Good spot, will fix this. We don't need this function at all afaics.

2021-04-29 07:42 UTC, QEDK commented on contracts/examples/erc1155-transfer/FxERC1155RootTunnel.sol
> +        rootToChildTokens[rootToken] = childToken;
Doable, cc @Raneet10 wrt ERC 1155

2021-05-01 15:25 UTC, QEDK commented on contracts/tokens/FxERC721.sol
> +        require(msg.sender == _fxManager, "Invalid sender");
Fixed. 💯

2021-05-01 15:25 UTC, QEDK commented on contracts/tokens/IFxERC721.sol
> +    function transfer(address from, address to, uint256 tokenId) external;
Fixed. 💯

2021-05-10 18:00 UTC, jdkanani commented
Can you please fix the CI?

2021-05-10 18:01 UTC, jdkanani commented
Can we also add mapped events for ERC20, ERC721 tunnels?

2021-05-11 07:37 UTC, QEDK commented
@jdkanani Should be done. There's a problem with upstream packages, not sure if it's been fixed yet.

2021-05-11 08:23 UTC, jdkanani approved these changes

2021-05-11 08:23 UTC, merged